#### Why can't we rely on Train Test Split

In [1]:
from sklearn.datasets import load_iris
import numpy as np

In [2]:
df = load_iris()

In [3]:
x = df['data']
y = df['target']

In [4]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
from sklearn.model_selection import train_test_split as tts 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [12]:
x_train,x_test,y_train,y_test = tts(x,y,test_size=0.3,random_state=4) #42, 10, 4, 5

KNN = KNeighborsClassifier(n_neighbors=5)
KNN

KNeighborsClassifier()

In [13]:
KNN.fit(x_train,y_train)
y_pred = KNN.predict(x_test)

In [14]:
accuracy_score(y_pred, y_test) # accuracy score will be diff diff , as per the diff diff random set selection
# then how will we rely on perticular one???
# Solution : we'll do bunch of trian-test-split, and will find the mean-score of that, That's the essence of CrossValidation!!!

0.9777777777777777

### K - Fold  Cross Validation (bacisally crossVal)

#### we'll devide dataset into 5 folds

In [15]:
from sklearn.model_selection import KFold

In [17]:
x = np.random.random(size =(25,5))
y = np.random.randint(low = 0, high = 2, size=25) # high 2 meand there will be 2 classes

In [18]:
x

array([[0.82952237, 0.62353428, 0.2975211 , 0.15577855, 0.66485302],
       [0.6316791 , 0.31669732, 0.90836523, 0.44041176, 0.94861505],
       [0.07850962, 0.18022842, 0.30036451, 0.86183078, 0.77743507],
       [0.22407569, 0.06047797, 0.69087399, 0.90348115, 0.16696253],
       [0.11879459, 0.14940845, 0.22504044, 0.14179427, 0.77146086],
       [0.05438093, 0.66494329, 0.08286704, 0.40451138, 0.92198308],
       [0.23663508, 0.66950732, 0.73452091, 0.44648379, 0.21605046],
       [0.18068875, 0.1885402 , 0.09837077, 0.69554005, 0.98501753],
       [0.68921966, 0.10557343, 0.24537708, 0.52970662, 0.14214539],
       [0.63695665, 0.48361075, 0.99104633, 0.06169101, 0.95655578],
       [0.0307264 , 0.70278514, 0.42105166, 0.79199126, 0.22331117],
       [0.55018872, 0.37993063, 0.42105703, 0.44863941, 0.73873055],
       [0.20569478, 0.5403755 , 0.62799139, 0.18968107, 0.67187269],
       [0.67917177, 0.9877014 , 0.17048817, 0.92289086, 0.37735306],
       [0.73564407, 0.97315628, 0.

In [19]:
y

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1])

In [20]:
kf = KFold(n_splits=6) # dataset will b splitted into 6 parts, but every split containd 4 values
for train_index, test_index in kf.split(x):
    print(train_index,test_index)

    # u can see the train and test indexes

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] [0 1 2 3 4]
[ 0  1  2  3  4  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] [5 6 7 8]
[ 0  1  2  3  4  5  6  7  8 13 14 15 16 17 18 19 20 21 22 23 24] [ 9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 17 18 19 20 21 22 23 24] [13 14 15 16]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 21 22 23 24] [17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [21 22 23 24]


In [ ]:
# still it doesn't solve 1 probles (usually we don't use k-folds in real world probles, however can use to see the tained and tested data)

#### What if there are unequal proportaions of classes in the Test set?

Stratified Sampling : let there r 2 classes blue and yellow, when we apply train-test-split we make sure that trianning set contains same proportion of classes as there was in datase and so wih the testing dataset also.

dataset = 3:2, training = 3:2, testing = 3:2

funciton in sklearn cross_val_score() which do cross validation with stratified sampling. This is the fun which we'r gonna apply in real life problem

## Cross_Val_Score (Classification)

In [21]:
from sklearn.model_selection import cross_val_score

In [22]:
data = load_iris()
x = data['data']
y = data['target']

In [23]:
KNN =  KNeighborsClassifier(n_neighbors=5)
scores = cross_val_score(KNN,x,y, cv=10,scoring='accuracy') #cv means K value
scores

array([1.        , 0.93333333, 1.        , 1.        , 0.86666667,
       0.93333333, 0.93333333, 1.        , 1.        , 1.        ])

In [24]:
scores.mean()

0.9666666666666668

In [25]:
for i in range(1,21):
    KNN = KNeighborsClassifier(n_neighbors=i)
    scores = cross_val_score(KNN, x,y, cv =10,scoring='accuracy')
    print(i,scores.mean())

1 0.96
2 0.9533333333333334
3 0.9666666666666666
4 0.9666666666666666
5 0.9666666666666668
6 0.9666666666666668
7 0.9666666666666668
8 0.9666666666666668
9 0.9733333333333334
10 0.9666666666666668
11 0.9666666666666668
12 0.9733333333333334
13 0.9800000000000001
14 0.9733333333333334
15 0.9733333333333334
16 0.9733333333333334
17 0.9733333333333334
18 0.9800000000000001
19 0.9733333333333334
20 0.9800000000000001


### cross_val_score (Regression)

herein, only difference is that scoring fun changes into regression problem, i.e. 'r2' rather than 'accuracy'

In [28]:
# from sklearn.metrics import SCORERS
# SCORERS.key() # check the list of scoring function